### ISSUE TITLE
npm test producing incorrect results

### ISSUE THREAD

**Issue by themanselmo** [learn-co-curriculum/phase-0-pac-3-what-is-a-test-lab#1]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

> Add a link to the assignment in Canvas here.

## Describe the bug
 instead of providing the expected output on first run, it produced this. 

$ npm test

> js-functions-lab@0.1.0 test
> mocha --timeout 5000 --reporter 'json' > .results.json & mocha

  1) "before all" hook

  0 passing (3s)
  1 failing

  1) "before all" hook:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at Object.done (node_modules/mocha-jsdom/index.js:70:7)
      at /mnt/d/Programming/FlatironSchool/code/phase0/phase-0-pac-3-what-is-a-test-lab/node_modules/jsdom/lib/jsdom.js:325:18
      at processTicksAndRejections (node:internal/process/task_queues:78:11)

Even if I continued with the lab accordingly (although difficult since I couldnt use my own test to debug, I could not proceed.
> Write a clear and concise description of what the bug is. Include the file and
> line number(s) if possible.

## What is the expected behavior?

> Write a clear and concise description of what you expected to happen.

## Screenshots

> If applicable, attach screenshots to help explain your problem.

## What OS are you using?

- [ ] OS X
- [ ] WSL
- [ ] Linux

## Any additional context?

> Add any other context about the problem here.

**Comment by lizbur10** [comment]
Hi @themanselmo ! Sorry you're running into this problem! 

For all of the labs where you're getting this error, you can try updating the following line in the package.json file:

`  "scripts": {
    "test": "mocha --timeout 5000 --reporter 'json' > .results.json & mocha"
  },`

Change the timeout setting to 10000, rerun `npm install` then try the test again. You can continue to bump it up if necessary.

If you continue to have problems with this issue, I suggest that you post a question in the #js-prework-support Slack channel. I was not able to recreate the issue when I ran the tests, which suggests that the problem may be with your local environment rather than the lab itself. 

I'm going to go ahead and close this issue and the others you posted on this same issue. 💙
