### ISSUE TITLE
error message when running test

### ISSUE THREAD

**Issue by amawalke** [learn-co-curriculum/phase-0-pac-3-what-is-a-test-lab#19]
mannywalker@Mannys-MacBook-Air phase-0-pac-3-what-is-a-test % learn test

> js-functions-lab@0.1.0 test
> mocha --timeout 5000 -R mocha-multi --reporter-options spec=-,json=.results.json

Hello-
I am receiving this error message when I attempt to complete this test. Please advise. Thank you!

Manny

  1) "before all" hook in "{root}"

  0 passing (178ms)
  1 failing

  1) "before all" hook in "{root}":
     TypeError: require(...).env is not a function
      at Context.<anonymous> (node_modules/mocha-jsdom/index.js:52:22)
      at process.processImmediate (node:internal/timers:471:21)

mannywalker@Mannys-MacBook-Air phase-0-pac-3-what-is-a-test %

**Comment by lizbur10** [comment]
Hi there! Thanks for raising this issue. Based on your description, it sounds like the
issue may be related to your environment setup rather than with the lesson
itself or the instructions. The curriculum team monitors these issues so that we
can fix typos and bugs in the curriculum, but we aren't equipped to provide
support.

To get help with your question, you should either:

- Reach out to your instructor (if you've started the program and have an
  instructor)
- Use the
  [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit)
  feature in Canvas to connect with a Technical Coach on the Academic Success
  Team

Please re-open this issue if you believe the lesson needs to be updated.

Hope you are able to get this resolved!
